Repository Azure/ms-rest-azure-env, pull requests merged in 2018-11, with the labels that each got.

#13 Rename NPM package to @azure/ms-rest-azure-env
  Changelog.md
  package.json
Labels: Unplanned-Sprint-126, in progress

#15 Add Azure Pipelines configuration
  azure-pipelines.yml
Labels: Unplanned-Sprint-126, in progress

#16 Add prepare step to NPM tasks
  package.json
Labels: in progress

#17 Remove Travis configuration
  .travis.yml
  package-lock.json
Labels: Unplanned-Sprint-126, in progress

#18 Update missing sample imports
  README.md
Labels: Unplanned-Sprint-126, in progress

#20 Add better sourcemap support for debugging
  .gitignore
  package-lock.json
  package.json
  rollup.config.js
Labels: Planned-Sprint-127, Started-Sprint-127, in progress

#22 Upgrade all dependencies
  package.json
Labels: in progress

#23 Update the NPM version after updating dependencies
  package.json
Labels: Planned-Sprint-127, in progress
